version: "3.9"
services:
  flyway:
    image: flyway/flyway
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ${PWD}/db_migrations:/flyway/sql
      - ${PWD}/docker-flyway.config:/flyway/conf/flyway.config
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PG_USER=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  web-app:
    image: voltron:latest
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/postgres
      - JDBC_USER=postgres
      - JDBC_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy