micronaut:
  application:
    name: hibernateDemo
datasources:
  default:
    db-type: postgres
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        connection:
          url: ${datasources.default.url}
          username: ${datasources.default.username}
          password: ${datasources.default.password}
    reactive: true
flyway:
  enabled: true
  datasources:
    default:
      enabled: false